### ISSUE TITLE
As a <traveler>, I want < a display of the European cities & their distances from Berlin on my screen > so that < I can see which cities are in my spectrum>.

### ISSUE THREAD

**Issue by erichvickers** [thea-k/CS1D2018-Project1#1]
Assumption:
Database is Connected.
Database holds the European Cities and their corresponding distances from Berlin. 

Story Point Estimation: 4

Priority: 1

List of Task and Tests: 

Task:
Read from the database and Display the European Cities in a bordered container.
Read from the database and Display the corresponding distance from Berlin next to the bordered container

Test: 
Check that the correct European Cities are displayed. 
Check that the correct corresponding distances are displayed next to the European Cities.

Definition of Done:  
Acceptance criteria is verified during Testing.
Unit testing - passed and completed.
Story is accepted by the Product Owner 
No memory Leaks.

**Comment by JakeSichley** [comment]
Functionality and UI complete.
