### ISSUE TITLE
As a <traveler>, I want < to visit the initial 11 European Cities starting at Paris> so that <I can see the most efficient trip starting at Paris >.

### ISSUE THREAD

**Issue by erichvickers** [thea-k/CS1D2018-Project1#3]
Assumptions:
Database is Connected. 
The initial 11 European Cities are in the database 
The corresponding distances of each European city is inside the Database.
The Starting location is Paris. 
The recursive functionality that takes the next closest city is completed. 
The Label generator functionality that populates the traditional food items for a given city is completed.
The functionality to make a purchase is completed.   
The functionality that takes account the number of purchases made is completed. 
The functionality that takes into account the distance traveled is completed. 

Story Point Estimation: 10

Priority: 2

List of Task and Tests: 

Task: 
Read in the European Cities from the Database.
Create a button for the “Initial 11 European Cities Trip”.  
Implement the Recursive function. 
Load the trip destinations.
Show the next stop(city) on the trip.
Show the distance traveled. 
Show the traditional food items at each city. 
Show the total purchases made the traveler at that location of the visit. 

Test: 
Check the that correct European Cities were read in. 
Check that the trip destination is in the most efficient order. 
Check that the next stop shows the correct city from the trip destination
Check that the purchases made are accounted for in the database. 

Definition of Done: 
Acceptance criteria is verified during Testing.
Unit testing - passed and completed.
Story is accepted by the Product Owner 
No memory Leaks.

**Comment by JakeSichley** [comment]
Functionality complete. UI will need updating.
