### ISSUE TITLE
As a <traveler>, I want < the next closest city to be my next stop and so on  > so that < my trip is very efficient >.

### ISSUE THREAD

**Issue by erichvickers** [thea-k/CS1D2018-Project1#4]
Assumptions:
The Database is connected. 
The Starting location is set. 
The European Cities on the trip are allocated. 
The corresponding distance to each cities is in the database. 
The functionality that tracks the distance is completed. 

Story Point Estimation: 10

Priority: 2

List of Task and Tests: 

Task: 
Read in the specified European Cities on the trip
Select the starting point (explain) 
Find the next closest city, this will become the next starting point and the previous starting point will be excluded from the list. 
Test:

Check that the correct cities are chosen.
Check the starting point has been confirmed (boolean). 
Check that the next closest city to the starting location is correct, and so on. 

Definition of Done: 
Acceptance criteria is verified during Testing.
Unit testing - passed and completed.
Story is accepted by the Product Owner 
No memory Leaks.

**Comment by JakeSichley** [comment]
The algorithm is functional and implemented.
