### ISSUE TITLE
As a <traveler>, I want < the total distance traveled to be displayed > so that < I can see how far we have traveled >.

### ISSUE THREAD

**Issue by erichvickers** [thea-k/CS1D2018-Project1#8]
Assumptions:
Database is Connected.
All the European cities and their corresponding distances to each other city are in the database. 
The recursive functionality that takes the next closest city is completed. 

Story Point Estimation: 2

Priority: 3

List of Task and Tests:

Task: 
The recursive functionality should have created the most efficient order in which to travel. 
Set a total distance variable, increment it with the distances to the next city from the recursive functionality list. 

Test:
Check that the total distance covered is accurate by adding the distances from the recursive functionality list. 

Definition of Done: 
Acceptance criteria is verified during Testing.
Unit testing - passed and completed.
Story is accepted by the Product Owner 
No memory Leaks.

**Comment by JakeSichley** [comment]
Functionality complete. UI will need updating.
